// AUTO-GENERATED by scripts/optimize-images.ts — do not edit by hand.
export const IMAGES = {
  "aerial-quarry": {
    width: 1024,
    height: 681,
    widths: [480, 768, 1024],
    placeholder:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAwCdASoYABAAPu1krU6ppaSiMAgBMB2JQBOkGQBgP2srwoGXvPkgAP6RtvxxrXRvyL1W+9EG++r8ECWC0zb+8VWh29PTH81ZU2krx3p/N+0aYWZLdaRMGrJAAA==",
  },
  "bulk-carrier-2": {
    width: 1024,
    height: 630,
    widths: [480, 768, 1024],
    placeholder:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQBACdASoYAA8APu1krU2ppaSiMAgBMB2JYwCdMoADTqZcyBOqaFxRAAD+wuXrnAI9ikGvJM96QEvUv8xeyaoioSJSfluj3YF8AA==",
  },
  "bulk-carrier": {
    width: 1024,
    height: 639,
    widths: [480, 768, 1024],
    placeholder:
      "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABQAgCdASoYAA8AA4BaJZgCdADydsVvQy+IEzAA/sjF1dmpCC2pE5Iq035bslxrT6tPLG5JoMiP3i21kszPE+iy042WJY60c0+LUaVXVqZlNvJTQAA=",
  },
  "cement-silos": {
    width: 731,
    height: 1024,
    widths: [480, 731],
    placeholder:
      "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAABwBgCdASoYACIAPuVkpk2pJiOiNVgIASAciWgAnTLLv/gUHjlq89u5GWz0Nhzfr14bY+TZnj/TbDclYAAA/nFgg+4UbUqPdRsHqqr7oPnLmv/A62+wbsKuMlRzFb8Hzh82d8XMiP5Sf4BWdNb9dB7XIWV1ime5bStStc0CJscJYhguMJIZZxRmy7Cf7DRQ2+L+oK2KPjyNQh8D2u6YVQH6Tt/lmw1+wzfqlfvXozQAAA==",
  },
  "clinker-stockpile": {
    width: 1024,
    height: 683,
    widths: [480, 768, 1024],
    placeholder:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQBACdASoYABAAPu1kqk4ppaQiMAgBMB2JZwDKABuDQ3vc/MvRtMVAGAD+xFhcFUtcuGwoTptMweUMOE0ecWwK11jkOEuiQroa/Qfjy0PxstZrGxH60IAA",
  },
  "concrete-pour": {
    width: 1024,
    height: 681,
    widths: [480, 768, 1024],
    placeholder:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JYwCsAA1HwE04JPNK2HAA/rZq4m0O6RWPcIRzMKgIGlgKoZaCj3qZ3o8/kT2YEHkhK0gFQRIvSSLeL9El7AAA",
  },
  "gypsum-quarry": {
    width: 1024,
    height: 715,
    widths: [480, 768, 1024],
    placeholder:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACQBACdASoYABEAPt1WpU2opKOiN/qoARAbiWkAy2ghybT3cMjHC70PsgEysCAA+p6wXyuWpaSLoKD4EQYKCVK00jo4bocssw0KGSjYKApqXD8NI9iDp60qAAA=",
  },
  "hong-kong-harbour": {
    width: 1024,
    height: 727,
    widths: [480, 768, 1024],
    placeholder:
      "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABQBACdASoYABEAPu1kqE2ppaOiMAgBMB2JYgCdOUAA5QwgCmPu10WFCyJAAP7Mx/MITebZWwiGSm+tYTm3s1ip1rsxcQ+0ktwuvKci7Z/k1ZJJ1CYI7CG7Dg4WyzJ4a4iQF1QA",
  },
  "hong-kong-night": {
    width: 1024,
    height: 684,
    widths: [480, 768, 1024],
    placeholder:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACQAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JZwAASVArCIj4THAAAP7pOjby8J8tdn+sOnOqvh+58oc8QZpUhwzWfTtHZFN8FAAAAA==",
  },
  "port-bluehour": {
    width: 1024,
    height: 683,
    widths: [480, 768, 1024],
    placeholder:
      "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACQAwCdASoYABAAPu1iqU2ppaQiMAgBMB2JaACw7CHRaV8E90JAAP7LtZxQHfbpJ08qFHBZT/FDmq2nw9vzhuYSxnfuLqUSpyQCXSI1Ev5KiLxQAAA=",
  },
  "port-dusk": {
    width: 1024,
    height: 679,
    widths: [480, 768, 1024],
    placeholder:
      "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAwCdASoYABAAPu1kqU4ppaOiMAgBMB2JZgCdIMgB98G2prUYA9SAAP5w4PuCqgQqZkhg4T3y4Pk3zCjMqRwgypY0LR9X+q0/vAAA",
  },
  "port-loading": {
    width: 1024,
    height: 683,
    widths: [480, 768, 1024],
    placeholder:
      "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAwCdASoYABAAPu1krU6ppaSiMAgBMB2JZgCdL1yEs6WCiHI45xIA/ke3paw9D8pu9IA+DA1Bv8RVkEvuAo1PdFQas3b5WMvbxeFbl3Q6T468Sqy5KvLhADH1cxxDYAA=",
  },
  "rebar-site": {
    width: 1024,
    height: 769,
    widths: [480, 768, 1024],
    placeholder:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAwCdASoYABIAPu1qqFAppiOiqA1RMB2JaQDJTAiIdThLsc+dAAD+25wk1fvCI9Bjtw09Z8eRhLeuvJcMm/j8+hHTmYqbmQAAAA==",
  },
  "site-inspection": {
    width: 1024,
    height: 683,
    widths: [480, 768, 1024],
    placeholder:
      "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQAwCdASoYABAAPu1iqk2ppaQiMAgBMB2JYgC2yBeFogLZizTrkwAA/u6hvnkvqzNolVc5ZIazQYZMsF5Y+fe+TGTPRrIOsrHlTTUugmaoGiP1bAT+UjGApXLzdPoyEEryBAAA",
  },
} as const;

export type ImageName = keyof typeof IMAGES;
