// AUTO-GENERATED by scripts/generate-world-map.ts — do not edit by hand.
import type { GeoPointId } from "~/content/geo";

export const WORLD_MAP = {
  width: 1000,
  height: 470,
  /** Static dot-grid layer (cached asset, kept out of the HTML and JS bundles). */
  dotsSrc: "/data/world-dots.svg",
} as const;

export const PROJECTED_POINTS: Record<GeoPointId, { readonly x: number; readonly y: number }> = {
  hkg: {
    x: 832.5,
    y: 172.9,
  },
  gzh: {
    x: 829,
    y: 169.8,
  },
  hph: {
    x: 812.2,
    y: 178.6,
  },
  bkk: {
    x: 802,
    y: 211.2,
  },
  jkt: {
    x: 821.9,
    y: 287.8,
  },
  fjr: {
    x: 662.4,
    y: 162,
  },
  soh: {
    x: 664,
    y: 165,
  },
  khi: {
    x: 693.4,
    y: 163,
  },
  suz: {
    x: 592,
    y: 143.5,
  },
  ist: {
    x: 577.1,
    y: 103.4,
  },
  jed: {
    x: 614.4,
    y: 176.2,
  },
  dmm: {
    x: 643.8,
    y: 157,
  },
  los: {
    x: 510.2,
    y: 236,
  },
  abj: {
    x: 487.9,
    y: 240.9,
  },
  dkr: {
    x: 448.1,
    y: 203.1,
  },
  mba: {
    x: 619.7,
    y: 279,
  },
  dar: {
    x: 618.3,
    y: 290.2,
  },
  cgp: {
    x: 767.4,
    y: 172.9,
  },
  cmb: {
    x: 740.4,
    y: 234.4,
  },
  mnl: {
    x: 859.9,
    y: 203.5,
  },
  bne: {
    x: 937.2,
    y: 372.1,
  },
  pom: {
    x: 941.8,
    y: 300.9,
  },
  rtm: {
    x: 510.8,
    y: 67.4,
  },
  pir: {
    x: 564.1,
    y: 114.2,
  },
  clo: {
    x: 269.4,
    y: 311.4,
  },
  hou: {
    x: 230.4,
    y: 144.4,
  },
  ssz: {
    x: 365.8,
    y: 358.6,
  },
};
