/**
 * Pre-computes a dot-matrix world map (Equal Earth projection) and the
 * projected positions of every trade-network point in `app/content/geo.ts`.
 * The runtime then renders a lightweight static SVG — no map library shipped.
 *
 * Run with: bun run assets:map
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { geoContains, geoEqualEarth } from "d3-geo";
import type { FeatureCollection, MultiPoint, MultiPolygon, Polygon } from "geojson";
import { feature } from "topojson-client";
import type { GeometryCollection, Topology } from "topojson-specification";
import { GEO_POINTS } from "../app/content/geo";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const WIDTH = 1000;
const HEIGHT = 470;
const STEP = 7; // dot pitch in map units
const MIN_LAT = -56; // drop Antarctica
const MAX_LAT = 84;

async function main() {
  const topo = JSON.parse(
    await readFile(join(root, "node_modules/world-atlas/land-50m.json"), "utf8"),
  ) as Topology<{ land: GeometryCollection }>;
  const land = feature(topo, topo.objects.land) as FeatureCollection<Polygon | MultiPolygon>;

  // Fit the projection to the inhabited latitude band so Antarctica is excluded
  // and the Arctic is not cropped.
  const frame: MultiPoint = {
    type: "MultiPoint",
    coordinates: [
      [-180, MIN_LAT],
      [180, MIN_LAT],
      [0, MIN_LAT],
      [-180, MAX_LAT],
      [180, MAX_LAT],
      [0, MAX_LAT],
    ],
  };
  const projection = geoEqualEarth().fitExtent(
    [
      [0, 0],
      [WIDTH, HEIGHT],
    ],
    frame,
  );

  const segments: string[] = [];
  for (let y = STEP / 2; y < HEIGHT; y += STEP) {
    // Offset alternate rows for a hexagonal, more organic pattern.
    const offset = Math.round(y / STEP) % 2 === 0 ? 0 : STEP / 2;
    for (let x = STEP / 2 + offset; x < WIDTH; x += STEP) {
      const lonLat = projection.invert?.([x, y]);
      if (!lonLat || lonLat[1] < MIN_LAT) continue;
      // Reject points outside the projection's curved outline (invert wraps them).
      const back = projection(lonLat);
      if (!back || Math.hypot(back[0] - x, back[1] - y) > 0.5) continue;
      if (land.features.some((f) => geoContains(f, lonLat))) {
        segments.push(`M${Math.round(x * 10) / 10} ${Math.round(y * 10) / 10}h0`);
      }
    }
  }

  const points = Object.fromEntries(
    GEO_POINTS.map((p) => {
      const xy = projection([p.coords[0], p.coords[1]]);
      if (!xy) throw new Error(`Cannot project ${p.id}`);
      return [p.id, { x: Math.round(xy[0] * 10) / 10, y: Math.round(xy[1] * 10) / 10 }];
    }),
  );

  const ts = `// AUTO-GENERATED by scripts/generate-world-map.ts — do not edit by hand.
import type { GeoPointId } from "~/content/geo";

export const WORLD_MAP = {
  width: ${WIDTH},
  height: ${HEIGHT},
  /** Static dot-grid layer (cached asset, kept out of the HTML and JS bundles). */
  dotsSrc: "/data/world-dots.svg",
} as const;

export const PROJECTED_POINTS: Record<GeoPointId, { readonly x: number; readonly y: number }> = ${JSON.stringify(points, null, 2)};
`;
  await writeFile(join(root, "app/components/map/world-map.generated.ts"), ts);
  await mkdir(join(root, "public/data"), { recursive: true });
  await writeFile(
    join(root, "public/data/world-dots.svg"),
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${WIDTH} ${HEIGHT}" width="${WIDTH}" height="${HEIGHT}"><path d="${segments.join("")}" fill="none" stroke="#71868a" stroke-width="2.4" stroke-linecap="round"/></svg>`,
  );
  console.log(`✔ World map generated (${segments.length} dots)`);

  await generateGlobeDots(land);
}

/**
 * Evenly distributed land dots for the 3D globe (Fibonacci sphere sampling),
 * written as a compact binary of Int16 pairs: [lat×100, lon×100, …].
 * Fetched lazily by the globe so it never weighs on the JS bundle.
 */
async function generateGlobeDots(land: FeatureCollection<Polygon | MultiPolygon>) {
  const SAMPLES = 24_000;
  const golden = Math.PI * (3 - Math.sqrt(5));
  const coords: number[] = [];
  for (let i = 0; i < SAMPLES; i++) {
    const y = 1 - (i / (SAMPLES - 1)) * 2;
    const theta = golden * i;
    const lat = (Math.asin(y) * 180) / Math.PI;
    const lon = (((((theta * 180) / Math.PI + 180) % 360) + 360) % 360) - 180;
    if (lat < MIN_LAT) continue;
    if (land.features.some((f) => geoContains(f, [lon, lat]))) {
      coords.push(Math.round(lat * 100), Math.round(lon * 100));
    }
  }
  await mkdir(join(root, "public/data"), { recursive: true });
  await writeFile(
    join(root, "public/data/globe-land.bin"),
    Buffer.from(new Int16Array(coords).buffer),
  );
  console.log(`✔ Globe dots generated (${coords.length / 2} dots)`);
}

await main();
