/**
 * Pre-computes a dot-matrix world map (Equal Earth projection) and the
 * projected positions of every trade-network point in `app/content/geo.ts`.
 * The runtime then renders a lightweight static SVG — no map library shipped.
 *
 * Run with: bun run assets:map
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { geoContains, geoEqualEarth } from "d3-geo";
import type { FeatureCollection, MultiPoint, MultiPolygon, Polygon } from "geojson";
import { feature } from "topojson-client";
import type { GeometryCollection, Topology } from "topojson-specification";
import { GEO_POINTS } from "../app/content/geo";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const WIDTH = 1000;
const HEIGHT = 470;
const STEP = 7; // dot pitch in map units
const MIN_LAT = -56; // drop Antarctica
const MAX_LAT = 84;

async function main() {
  const topo = JSON.parse(
    await readFile(join(root, "node_modules/world-atlas/land-50m.json"), "utf8"),
  ) as Topology<{ land: GeometryCollection }>;
  const land = feature(topo, topo.objects.land) as FeatureCollection<Polygon | MultiPolygon>;

  // Fit the projection to the inhabited latitude band so Antarctica is excluded
  // and the Arctic is not cropped.
  const frame: MultiPoint = {
    type: "MultiPoint",
    coordinates: [
      [-180, MIN_LAT],
      [180, MIN_LAT],
      [0, MIN_LAT],
      [-180, MAX_LAT],
      [180, MAX_LAT],
      [0, MAX_LAT],
    ],
  };
  const projection = geoEqualEarth().fitExtent(
    [
      [0, 0],
      [WIDTH, HEIGHT],
    ],
    frame,
  );

  const segments: string[] = [];
  for (let y = STEP / 2; y < HEIGHT; y += STEP) {
    // Offset alternate rows for a hexagonal, more organic pattern.
    const offset = Math.round(y / STEP) % 2 === 0 ? 0 : STEP / 2;
    for (let x = STEP / 2 + offset; x < WIDTH; x += STEP) {
      const lonLat = projection.invert?.([x, y]);
      if (!lonLat || lonLat[1] < MIN_LAT) continue;
      // Reject points outside the projection's curved outline (invert wraps them).
      const back = projection(lonLat);
      if (!back || Math.hypot(back[0] - x, back[1] - y) > 0.5) continue;
      if (land.features.some((f) => geoContains(f, lonLat))) {
        segments.push(`M${Math.round(x * 10) / 10} ${Math.round(y * 10) / 10}h0`);
      }
    }
  }

  const points = Object.fromEntries(
    GEO_POINTS.map((p) => {
      const xy = projection([p.coords[0], p.coords[1]]);
      if (!xy) throw new Error(`Cannot project ${p.id}`);
      return [p.id, { x: Math.round(xy[0] * 10) / 10, y: Math.round(xy[1] * 10) / 10 }];
    }),
  );

  const ts = `// AUTO-GENERATED by scripts/generate-world-map.ts — do not edit by hand.
import type { GeoPointId } from "~/content/geo";

export const WORLD_MAP = {
  width: ${WIDTH},
  height: ${HEIGHT},
  dotPitch: ${STEP},
  dots: ${JSON.stringify(segments.join(""))},
} as const;

export const PROJECTED_POINTS: Record<GeoPointId, { readonly x: number; readonly y: number }> = ${JSON.stringify(points, null, 2)};
`;
  await writeFile(join(root, "app/components/map/world-map.generated.ts"), ts);
  console.log(`✔ World map generated (${segments.length} dots)`);
}

await main();
