/**
 * Converts the curated source photos in `scripts/images-source` into
 * responsive AVIF + WebP renditions in `public/images`, and writes a typed
 * manifest (intrinsic size + blurred LQIP placeholder) for the <Picture /> component.
 *
 * Run with: bun run assets:images
 */
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { basename, dirname, extname, join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const srcDir = join(root, "scripts/images-source");
const outDir = join(root, "public/images");
const manifestPath = join(root, "app/lib/images.generated.ts");

/** Target rendition widths — never upscaled beyond the source. */
const WIDTHS = [480, 768, 1024, 1600] as const;

type Entry = {
  width: number;
  height: number;
  widths: number[];
  placeholder: string;
};

async function processImage(file: string): Promise<[string, Entry]> {
  const name = basename(file, extname(file));
  const input = sharp(join(srcDir, file)).rotate();
  const meta = await input.metadata();
  if (!meta.width || !meta.height) throw new Error(`Cannot read size of ${file}`);

  const widths = [...new Set(WIDTHS.map((w) => Math.min(w, meta.width ?? w)))].sort(
    (a, b) => a - b,
  );

  await Promise.all(
    widths.flatMap((w) => [
      input
        .clone()
        .resize({ width: w, withoutEnlargement: true })
        .avif({ quality: 52, effort: 6 })
        .toFile(join(outDir, `${name}-${w}.avif`)),
      input
        .clone()
        .resize({ width: w, withoutEnlargement: true })
        .webp({ quality: 74, effort: 6 })
        .toFile(join(outDir, `${name}-${w}.webp`)),
    ]),
  );

  const lqip = await input.clone().resize({ width: 24 }).blur(1.2).webp({ quality: 40 }).toBuffer();

  return [
    name,
    {
      width: meta.width,
      height: meta.height,
      widths,
      placeholder: `data:image/webp;base64,${lqip.toString("base64")}`,
    },
  ];
}

async function main() {
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  const files = (await readdir(srcDir)).filter((f) => /\.(jpe?g|png|webp)$/i.test(f)).sort();
  const entries = await Promise.all(files.map(processImage));

  const ts = `// AUTO-GENERATED by scripts/optimize-images.ts — do not edit by hand.
export const IMAGES = ${JSON.stringify(Object.fromEntries(entries), null, 2)} as const;

export type ImageName = keyof typeof IMAGES;
`;
  await writeFile(manifestPath, ts);
  console.log(`✔ Optimised ${entries.length} images → public/images`);
}

await main();
